name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      auto_version:
        required: true
        default: 'patch'
        description: Choose auto-versioning type
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Parse current version
      run: |
        CURRENT_VERSION=$(git describe --tags --abbrev=0)
        major=$(echo $CURRENT_VERSION | cut -d. -f1)
        echo "major=${major}" >> $GITHUB_ENV
        minor=$(echo $CURRENT_VERSION | cut -d. -f2)
        echo "minor=${minor}" >> $GITHUB_ENV
        patch=$(echo $CURRENT_VERSION | cut -d. -f3)
        echo "patch=${patch}" >> $GITHUB_ENV
        echo "Current version $major.$minor.$patch"

    - name: Increment version by major
      if: contains(github.event.inputs.auto_version, 'major')
      run: |
        NEW_VERSION=$(echo "$(($major+1)).$minor.$patch")
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: Increment version by minor
      if: contains(github.event.inputs.auto_version, 'minor')
      run: |
        NEW_VERSION=$(echo "$major.$(($minor+1)).$patch")
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: Increment version by patch
      if: contains(github.event.inputs.auto_version, 'patch')
      run: |
        NEW_VERSION=$(echo "$major.$minor.$(($patch+1))")
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: New version
      run: echo "New version $NEW_VERSION"
    
    - name: Update version in POM
      run: mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Create a new tag
      run: |
        git config user.email "robertasvi@users.noreply.github.com"
        git config user.name "robertasvi"
        git add -A
        git commit -a -m "Version increment $NEW_VERSION"
        git push origin master
        git tag $NEW_VERSION
        git push --follow-tags
        git push --tags

  build:
    needs:
      - version
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    
      - name: Build with Maven
        run: mvn -B package --file pom.xml
    