name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      auto_version:
        required: true
        default: 'patch'
        description: Choose auto-versioning type
        type: choice
        options:
          - major
          - minor
          - patch
env:
  CURRENT_VERSION:
  NEW_VERSION:
  major:
  minor:
  patch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Current version
      run: |
        echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        echo ${{env.CURRENT_VERSION}}
        echo "major=$(echo ${{env.CURRENT_VERSION}} | cut -d. -f1)" >> $GITHUB_ENV
        echo "minor=$(echo ${{env.CURRENT_VERSION}} | cut -d. -f2)" >> $GITHUB_ENV
        echo "patch=$(echo ${{env.CURRENT_VERSION}} | cut -d. -f3)" >> $GITHUB_ENV

    - name: Increment version by major
      if: contains(github.event.inputs.auto_version, 'major')
      run: |
        echo "NEW_VERSION=$(echo "$((${{env.major}}+1)).${{env.minor}}.${{env.patch}}")" >> $GITHUB_ENV
        echo ${{env.NEW_VERSION}}

    - name: Increment version by minor
      if: contains(github.event.inputs.auto_version, 'minor')
      run: |
        echo "NEW_VERSION=$(echo "${{env.major}}.$((${{env.minor}}+1)).${{env.patch}}")" >> $GITHUB_ENV
        echo ${{env.NEW_VERSION}}

    - name: Increment version by patch
      if: contains(github.event.inputs.auto_version, 'patch')
      run: |
        echo "NEW_VERSION=$(echo "${{env.major}}.${{env.minor}}.$((${{env.patch}}+1))")" >> $GITHUB_ENV
        echo ${{env.NEW_VERSION}}

    - name: Create new version tag
      run: |
        mvn versions:set -DnewVersion=${{env.NEW_VERSION}}
        git config user.email "robertasvi@users.noreply.github.com"
        git config user.name "robertasvi"
        git add -A
        git commit -a -m "Version increment ${{env.NEW_VERSION}}"
        git push origin master
        git tag ${{env.NEW_VERSION}}
        git push --follow-tags
        git push --tags

    - name: Build with Maven
      run: mvn -B package --file pom.xml
