name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      auto_version:
        required: true
        default: 'minor'
        description: Choose auto-versioning type
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven 
      run: |
        # mvn -B package --file pom.xml
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo $VERSION
        major=$(echo $VERSION | cut -d. -f1)
        minor=$(echo $VERSION | cut -d. -f2)
        patch=$(echo $VERSION | cut -d. -f3)
        minor=$((minor+1))
        echo "$major.$minor.$patch"

