name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      auto_version:
        required: true
        default: 'patch'
        description: Choose auto-versioning type
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.0
      major: 0
      minor: 0
      patch: 0
      RELEASE: 0.0.0
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Semantic version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
        echo ${{env.VERSION}}
        major=$(echo ${{env.VERSION}} | cut -d. -f1) >> $GITHUB_ENV
        minor=$(echo ${{env.VERSION}} | cut -d. -f2) >> $GITHUB_ENV
        patch=$(echo ${{env.VERSION}}| cut -d. -f3) >> $GITHUB_ENV
    - name: Major version
      if: contains(github.event.inputs.auto_version, 'major')
      run: |
        major=$((${{env.major}}+1)) >> $GITHUB_ENV
    - name: Minor version
      if: contains(github.event.inputs.auto_version, 'minor')
      run: |
        minor=$((${{env.minor}}+1)) >> $GITHUB_ENV
    - name: Patch version
      if: contains(github.event.inputs.auto_version, 'patch')
      run: |
        patch=$((${{env.patch}}+1)) >> $GITHUB_ENV

    - name: Release version
      run: |
        RELEASE=$(echo "${{env.major}}.${{env.minor}}.${{env.patch}}") >> $GITHUB_ENV
        mvn versions:set -DnewVersion=${{env.RELEASE}}
        git config user.email "robertasvi@users.noreply.github.com"
        git config user.name "robertasvi"
        git add -A
        git commit -a -m "Version increment ${{env.RELEASE}})"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.ref }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
